# Generated by Django 4.2.7 on 2024-01-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopProducts',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=60)),
                ('product_price', models.IntegerField()),
                ('product_processor', models.CharField(default='', max_length=60)),
                ('product_gpu', models.CharField(default='', max_length=60)),
                ('product_ram', models.CharField(default='', max_length=60)),
                ('product_battery', models.CharField(default='', max_length=30)),
                ('product_display', models.CharField(default='', max_length=30)),
                ('product_storage', models.CharField(default='', max_length=30)),
                ('product_description', models.CharField(default='', max_length=300)),
                ('product_image', models.ImageField(default='', upload_to='kleemoapp/images')),
                ('release_date', models.DateField()),
                ('market_share', models.JSONField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MobileProducts',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=60)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_chipset', models.CharField(default='', max_length=60)),
                ('product_gpu', models.CharField(default='', max_length=60)),
                ('product_ram_storage', models.CharField(default='', max_length=60)),
                ('product_battery', models.CharField(default='', max_length=20)),
                ('product_screen_size', models.CharField(default='', max_length=10)),
                ('product_main_camera', models.CharField(default='', max_length=30)),
                ('product_front_camera', models.CharField(default='', max_length=30)),
                ('product_fast_charging', models.CharField(default='', max_length=10)),
                ('product_sim_support', models.CharField(default='', max_length=30)),
                ('product_description', models.CharField(default='', max_length=300)),
                ('product_image', models.ImageField(default='', upload_to='kleemoapp/images')),
                ('release_date', models.DateField()),
                ('market_share', models.JSONField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SmartWatchProducts',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=60)),
                ('product_price', models.IntegerField()),
                ('product_water_resistant', models.CharField(default='', max_length=60)),
                ('product_sensor', models.CharField(default='', max_length=60)),
                ('product_charger_type', models.CharField(default='', max_length=60)),
                ('product_battery_life', models.CharField(default='', max_length=30)),
                ('product_display', models.CharField(default='', max_length=30)),
                ('product_storage', models.CharField(default='', max_length=30)),
                ('product_description', models.CharField(default='', max_length=300)),
                ('product_image', models.ImageField(default='', upload_to='kleemoapp/images')),
                ('release_date', models.DateField()),
                ('market_share', models.JSONField(default=0)),
            ],
        ),
    ]
