# Generated by Django 4.2.7 on 2024-01-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleemoapp', '0002_alter_mobileproducts_market_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopproducts',
            name='market_share',
            field=models.JSONField(),
        ),
    ]
