# Generated by Django 4.2.7 on 2024-01-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kleemoapp', '0004_alter_smartwatchproducts_market_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.CharField(max_length=20)),
                ('product_id', models.PositiveIntegerField()),
            ],
        ),
    ]
